chore: allow code-suggester releases
googleapis/sloth pull request #765
Opened 2020-08-04 17:19 UTC by chingor13

Autorelease still reads this file for determining which repositories can be released

2020-08-04 17:19 UTC, bcoe approved these changes

2020-08-04 17:20 UTC, bcoe requested changes
we could circumvent this with `release-please`.

2020-08-04 17:54 UTC, JustinBeckwith commented
@bcoe I still would like to add this to repos.json for SLO tracking 😆 Are you ok with landing it, and also tracking the issue to use release-please?

2020-08-08 01:35 UTC, bcoe approved these changes

2020-08-08 01:40 UTC, merged