chore: add runtimeconfig to Cloud/GCP denylist
googleapis/sloth pull request #940
Opened 2021-06-02 23:34 UTC by danoscarmike

2021-06-02 23:43 UTC, JustinBeckwith approved these changes

2021-06-02 23:43 UTC, JustinBeckwith requested changes

2021-06-02 23:43 UTC, JustinBeckwith commented on src/services.json
> +        "baremetalsolutions",
Was this intentional?

2021-06-02 23:43 UTC, JustinBeckwith commented on src/services.json
> +}
Please add my newline back 🙃

2021-06-03 00:24 UTC, danoscarmike commented on src/services.json
> +        "baremetalsolutions",
Nope

2021-06-03 00:38 UTC, JustinBeckwith approved these changes

2021-06-03 00:38 UTC, merged